theme: jekyll-theme-cayman

title: DSpace 7 REST API Tutorial
description: "Learn the new interface for DSpace Client Apps"
baseurl: "/DSpace7RestTutorial"
url: "http://dspace-labs.github.io/DSpace7RestTutorial"
theme: jekyll-theme-cayman
show_downloads: false

# --------------------------------
# Custom additions for the tutorial navigation bar
# --------------------------------

# src_path - used to construct nested links to code files
restService: https://dspace7.4science.it/dspace-spring-rest

# nav_style: menu or button
nav_style: menu
nav:
  - {name: Home, path: "/"}
  - {name: Installation Pre-requisites, path: "/preparation"}
  - {name: "Exercise 1 - HAL Browser", path: "/exercise1"}
  - {name: "Exercise 2", path: "/exercise2"}
  - {name: "Exercise 3", path: "/exercise3"}
  - {name: "Exercise 4", path: "/exercise4"}
